name: ${name}
main: ${main}
version: ${version}
author: ${author}
description: ${description}
api-version: ${apiversion}
website: ${website}
depend:
  - "kLoader"
commands:
  advent:
    aliases: [advent, adventskalender, adventcalendar]
    usage: /advent [give|set|reload|reset]
    description: Main command for the advent calendar plugin